version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapi:1
    ports:
      - "80:8080"
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017/
    networks:
      - db_net

  mongo:
    image: mongo:4.4.25
    volumes:
      - mongo-data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - db_net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - db_net

networks:
  db_net:

volumes:
  mongo-data:
